---
- name: Create EC2 instance
  hosts: localhost
  gather_facts: no  # Disable gathering facts for localhost

  tasks:
    - name: Create EC2 instance
      amazon.aws.ec2_instance:
        instance_type: t2.micro
        image_id: ami-05c13eab67c5d8861
        key_name: keyforDestop
        region: us-east-1
        security_group: launch-wizard-5
        count: 1
        tags:
          Name: Tom-instance
      register: ec2

    - name: Wait for SSH to become available
      wait_for:
        host: "{{ ec2.interfaces[0].association.public_ip }}"
        port: 22
        state: started         

