---
- name: Configure and Install Tomcat on Amazon Linux EC2
  hosts: all
  remote_user: ec2-user
    
  vars:
    #username: "admin"
    #myroles: "manager-gui,manager-script"
    #userport: "8080"

  tasks:   

    - name: Set hostname to 'tomcat'
      hostname:
        name: tomcat
      become: yes

    - name: Install required packages
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - git
        - wget
        - java-11
        - unzip
        - cronie
      become: yes

    # - name: Change working directory to /opt
    #   command: cd /opt

    - name: Download latest Tomcat
      become: yes
      shell: |
        wget {{ link }}
        unzip apache*.zip
        rm -rf apache*.zip
      args:
        chdir: /opt
        executable: /bin/bash

    - name: Rename Tomcat for good naming convention
      become: yes
      shell: mv apache*[0-9] tomcat9
      args:
        chdir: /opt
      

    - name: Set executable permissions
      become: yes
      file:
        path: /opt/tomcat9
        recurse: yes
        mode: '0777'
      

    - name: Change ownership to ec2-user
      become: yes
      command: chown -R ec2-user /opt/tomcat9   
    

    - name: Set up the tomcat port
      ansible.builtin.replace:
        path: /opt/tomcat9/conf/server.xml
        after: '\s+Define a non-SSL/TLS HTTP/1.1 Connector on port 8080'
        before: '\s+connectionTimeout="20000"'
        regexp: '8080'
        replace: '{{userport}}'



    - name: Copy tomcat.service to system
      become: yes
      ansible.builtin.copy:      
        src: /mnt/c/Users/kochf/Downloads/myscripts/tomcat.service
        dest: /etc/systemd/system/
  

    - name: Start Tomcat Service
      become: yes
      systemd:
        name: tomcat.service
        state: started

    - name: Enable Tomcat Service at Boot
      become: yes
      systemd:
        name: tomcat.service
        enabled: yes
    
    - name: Start commenting before Valve      
      lineinfile:
        path: /opt/tomcat9/webapps/manager/META-INF/context.xml
        insertbefore: 'Valve'
        line: '<!-- ' # make sure to put the space after <!--
        state: present

    - name: Close the comment after the allow section      
      lineinfile:
        path: /opt/tomcat9/webapps/manager/META-INF/context.xml
        insertafter: 'allow'
        line: '--> ' ## make sure to put the space after -->
        state: present
    
    - name: Modify tomcat-users.xml
      lineinfile:
        path: /opt/tomcat9/conf/tomcat-users.xml
        insertbefore: '</tomcat-users>'
        line: '<user username="{{ username }}" password="{{ password }}" roles="{{ myroles }}"/>'
      become: yes    

    - name: Going back to the home folder
      command: cd