---
- hosts: all
  tasks:
  - name: Create EC2 instance
    amazon.aws.ec2_instance:
      key_name: keyforDestop
      instance_type: t2.micro
      ami: ami-0fc5d935ebf8bc3bc
      region: us-east-1
      security_group: launch-wizard-5
      count: 1
      tags:
        Name: my-ec2-instance
      wait: yes
    register: ec2

  - name: Get EC2 Instance Public IP Address
    amazon.aws.ec2_instance_info:
      #region: us-east-1
      #service: ec2
      #action: describe_instances
      filters:
        instance-id: "{{ ec2.instances[0].instance_id }}"
      register: ec2_instance_info   

  - name: Wait until the string "completed" is in the file /tmp/foo before continuing
    ansible.builtin.wait_for:
      host: "{{ ec2_instance_info.instances[0].network_interfaces[0].association.public_ip }}"
      port: 22
      delay: 60
      timeout: 320
      state: started
        

  - name: Deploy Nginx
    hosts: "{{ ec2_instance_info.instances[0].network_interfaces[0].association.public_ip }}"
    become: yes
    tasks:
    - name: start deploying 
      apt:
        name: nginx
        state: present

    - name: Start Nginx service
      service:
        name: nginx
        state: started
